# Generated by Django 4.2.7 on 2024-01-02 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('login_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('qualification', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('gstin_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.TextField()),
                ('pincode1', models.CharField(max_length=6)),
                ('contact_person1', models.CharField(max_length=255)),
                ('mobile_no1', models.CharField(max_length=10)),
                ('contact_person_email1', models.EmailField(max_length=254)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('place_of_testing', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('pincode2', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person2', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no2', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person_email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('city1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city1', to='account.city')),
                ('city2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city2', to='account.city')),
                ('country1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country1', to='account.country')),
                ('country2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country2', to='account.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cus_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cus_modified_by', to=settings.AUTH_USER_MODEL)),
                ('state1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state1', to='account.state')),
                ('state2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state2', to='account.state')),
            ],
        ),
    ]
