# Generated by Django 4.2.7 on 2024-01-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_person_email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
