# Generated by Django 4.2.7 on 2024-01-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_employee_dob_alter_employee_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
