# Generated by Django 4.2.7 on 2024-01-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customer_code_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
