# Generated by Django 4.2.7 on 2024-01-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_employee_branch_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
