# Generated by Django 4.2.7 on 2024-01-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
