# Generated by Django 4.2.7 on 2024-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_customer_email_alter_customer_gstin_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_quatation_customer',
            field=models.BooleanField(default=False),
        ),
    ]
