# Generated by Django 4.2.7 on 2024-12-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_customer_is_quatation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pincode1',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
