# Generated by Django 4.2.7 on 2024-01-02 09:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fully_paid', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('invoice_no', models.CharField(max_length=20, null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=6, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid_date', models.DateField(blank=True, null=True)),
                ('invoice_image', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price_per_sample', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('report_template', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.test')),
            ],
        ),
        migrations.CreateModel(
            name='SalesMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_mode', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice_test')),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.report_template')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.test')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=6)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.ManyToManyField(to='payment.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice_files/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.salesmode'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.tax'),
        ),
        migrations.CreateModel(
            name='Expense_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narration', models.TextField()),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.expense')),
                ('expense_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.expense_user')),
            ],
        ),
    ]
