# Generated by Django 4.2.7 on 2024-01-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_expense_entry_created_by_expense_entry_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_test',
            name='invoice_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
