# Generated by Django 4.2.7 on 2024-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_invoice_test_invoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='place_of_testing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
