# Generated by Django 4.2.7 on 2024-01-05 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_invoice_tax_invoice_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_File_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_user', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='invoice_file',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.invoice_file_category'),
        ),
    ]
