# Generated by Django 4.2.7 on 2024-01-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_invoice_file_category_invoice_file_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_file_category',
            old_name='expense_user',
            new_name='name',
        ),
    ]
