# Generated by Django 4.2.7 on 2024-01-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_expense_user_invoice_file_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_file',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.invoice'),
        ),
    ]
