# Generated by Django 4.2.7 on 2024-01-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_delete_expense_user'),
        ('payment', '0009_alter_invoice_file_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.ManyToManyField(blank=True, null=True, to='general.tax'),
        ),
    ]
