# Generated by Django 4.2.7 on 2024-01-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_invoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_test',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=6),
        ),
    ]
