# Generated by Django 4.2.7 on 2024-01-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_invoice_test_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_test',
            name='report_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
