# Generated by Django 4.2.7 on 2024-01-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_employee_signature'),
        ('payment', '0012_alter_invoice_test_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_test',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
    ]
