# Generated by Django 4.2.7 on 2024-01-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_invoice_test_created_by_invoice_test_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sales_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.salesmode'),
        ),
    ]
