# Generated by Django 4.2.7 on 2024-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_invoice_sales_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_test',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
