# Generated by Django 4.2.7 on 2024-01-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_invoice_upi_alter_invoice_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='bank',
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='upi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='invoice_no',
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.invoice'),
        ),
    ]
