# Generated by Django 4.2.7 on 2024-01-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_employee_role'),
        ('payment', '0021_remove_receipt_bank_receipt_amount_receipt_upi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_test',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
