# Generated by Django 4.2.7 on 2024-01-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_receipt_created_by_receipt_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=6),
        ),
    ]
