# Generated by Django 4.2.7 on 2024-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_remove_invoice_test_customer_receipt_neft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
