# Generated by Django 4.2.7 on 2024-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_receipt_tds_alter_invoice_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_test',
            name='is_authorised_signatory',
            field=models.BooleanField(default=False),
        ),
    ]
