# Generated by Django 4.2.7 on 2024-12-19 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_useractivity'),
        ('general', '0004_alter_material_template'),
        ('payment', '0030_invoice_is_old_invoice_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ManyToManyField(blank=True, to='general.tax')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quotation_image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_authorised_signatory', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items_modified', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='payment.quotation')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.test')),
            ],
        ),
    ]
