# Generated by Django 4.2.7 on 2024-12-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_quotation_quotationitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
