# Generated by Django 4.2.7 on 2024-12-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_rename_unit_price_quotationitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='total',
        ),
        migrations.CreateModel(
            name='QuotationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports/')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_reports', to='payment.quotation')),
            ],
        ),
    ]
