# Generated by Django 4.2.7 on 2024-12-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_remove_quotation_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
