# Generated by Django 4.2.7 on 2024-12-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_quotation_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation_image',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_qr',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/'),
        ),
    ]
