# Generated by Django 4.2.7 on 2024-12-20 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0036_quotation_created_by_quotation_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationreport',
            name='report',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='price_per_sample',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationreport',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationreport',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_reports_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationreport',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationreport',
            name='quotation_file',
            field=models.FileField(default=1, upload_to='quotation_reports/'),
            preserve_default=False,
        ),
    ]
