# Generated by Django 4.2.7 on 2024-12-21 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0037_remove_quotationreport_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='is_authorised_signatory',
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='price_per_sample',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Invoice_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_file', models.FileField(upload_to='invoice_reports/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_reports_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_reports_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
