# Generated by Django 4.2.7 on 2024-12-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0039_invoicereport_alter_invoice_test_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicereport',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='quotationreport',
            name='quotation_file',
        ),
    ]
