# Generated by Django 4.2.7 on 2024-12-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_useractivity'),
        ('payment', '0040_remove_invoicereport_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='account.customer'),
        ),
    ]
