# Generated by Django 4.2.7 on 2024-12-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_material_template'),
        ('payment', '0041_alter_quotation_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationreport',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='quotationreport',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='test',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='test',
            field=models.ManyToManyField(blank=True, to='general.test'),
        ),
    ]
