# Generated by Django 4.2.7 on 2024-12-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_material_template'),
        ('payment', '0042_remove_quotationreport_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='test',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='general.test'),
            preserve_default=False,
        ),
    ]
