# Generated by Django 4.2.7 on 2024-12-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0043_remove_quotationitem_test_quotationitem_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereport',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoice_report/'),
        ),
        migrations.AddField(
            model_name='quotationreport',
            name='quotation_file',
            field=models.FileField(blank=True, null=True, upload_to='quotation/'),
        ),
    ]
