# Generated by Django 4.2.7 on 2024-12-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0044_invoicereport_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicereport',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_reports', to='payment.invoice'),
        ),
    ]
