# Generated by Django 4.2.7 on 2024-12-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0045_alter_invoicereport_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
