# Generated by Django 4.2.7 on 2025-04-26 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0047_customerdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiscount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discount_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='discount',
            field=models.FloatField(),
        ),
    ]
