# Generated by Django 4.2.7 on 2025-07-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0050_alter_customerdiscount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='after_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='before_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
