# Generated by Django 4.2.7 on 2025-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0052_invoicediscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicediscount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
