# Generated by Django 4.2.7 on 2025-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0054_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
