# Generated by Django 4.2.7 on 2025-07-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_expense_created_by_alter_expense_modified_by'),
        ('payment', '0055_alter_invoice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_test',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_invoice', to='general.test'),
        ),
    ]
