# Generated by Django 4.2.7 on 2025-07-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0056_alter_invoice_test_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_file',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_files', to='payment.invoice'),
        ),
    ]
