# Generated by Django 4.2.7 on 2025-07-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0057_alter_invoice_file_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='invoice_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipts', to='payment.invoice'),
        ),
    ]
