# Generated by Django 4.2.7 on 2025-07-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0059_historicaltest_report_historicalsalesmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='after_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='before_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='after_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='before_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
