# Generated by Django 4.2.7 on 2025-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0060_historicalquotation_after_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotationitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
