# Generated by Django 4.2.7 on 2025-07-30 05:29

from django.db import migrations, models
import payment.models.quatation_models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0061_historicalquotationitem_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquotation',
            name='date_created',
            field=models.DateField(default=payment.models.quatation_models.today),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date_created',
            field=models.DateField(default=payment.models.quatation_models.today),
        ),
    ]
