# Generated by Django 4.2.7 on 2025-08-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_employee_user'),
        ('payment', '0062_alter_historicalquotation_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice_test',
            name='primary_signature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.employee'),
        ),
        migrations.AddField(
            model_name='historicalinvoice_test',
            name='secondary_signature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.employee'),
        ),
        migrations.AddField(
            model_name='invoice_test',
            name='primary_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_tests_as_primary_signature', to='account.employee'),
        ),
        migrations.AddField(
            model_name='invoice_test',
            name='secondary_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_tests_as_secondary_signature', to='account.employee'),
        ),
    ]
