# Generated by Django 4.2.7 on 2025-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0063_historicalinvoice_test_primary_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice_test',
            name='primary_authorised_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinvoice_test',
            name='secondary_authorised_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_test',
            name='primary_authorised_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_test',
            name='secondary_authorised_signature',
            field=models.BooleanField(default=False),
        ),
    ]
