# Generated by Django 4.2.7 on 2025-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0064_historicalinvoice_test_primary_authorised_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice_test',
            name='without_primary_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinvoice_test',
            name='without_secondary_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_test',
            name='without_primary_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_test',
            name='without_secondary_signature',
            field=models.BooleanField(default=False),
        ),
    ]
