# Generated by Django 4.2.7 on 2025-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0066_quotationtax_invoicetax_historicalquotationtax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicetax',
            name='tax_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalquotationtax',
            name='tax_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicetax',
            name='tax_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationtax',
            name='tax_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
