# Generated by Django 4.2.7 on 2025-08-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0067_historicalinvoicetax_tax_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='tax',
        ),
        migrations.AlterField(
            model_name='invoicetax',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_details', to='payment.invoice'),
        ),
        migrations.AlterField(
            model_name='quotationtax',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_tax_details', to='payment.quotation'),
        ),
    ]
