# Generated by Django 4.2.7 on 2025-08-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0068_remove_invoice_tax_remove_quotation_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquotationtax',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalquotationtax',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalquotationtax',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='historicalquotationtax',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='quotationtax',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoicetax',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoicetax',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationtax',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotationtax',
            name='quotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_taxes', to='payment.quotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationtax',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicetax',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_taxes', to='payment.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicetax',
            name='tax_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotationtax',
            name='tax_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalInvoiceTax',
        ),
        migrations.DeleteModel(
            name='HistoricalQuotationTax',
        ),
    ]
