# Generated by Django 4.2.7 on 2025-08-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0070_historicalinvoicetax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationtax',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotationtax_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
