# Generated by Django 4.2.7 on 2024-01-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_expense_entry_expense_user'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense_User',
        ),
    ]
