# Generated by Django 4.2.7 on 2024-01-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_delete_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_template',
            name='template',
            field=models.TextField(null=True),
        ),
    ]
