# Generated by Django 4.2.7 on 2024-01-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_report_template_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='template',
            field=models.TextField(null=True),
        ),
    ]
